PREFIX xsd: &lt;http://www.w3.org/2001/XMLSchema#&gt;
PREFIX meteo: &lt;http://purl.org/ns/meteo#&gt;
PREFIX : &lt;http://5stardata.info/ja/gtd-5.html#&gt;

SELECT ?tempC from &lt;http://any23.org/rdfxml/http://5stardata.info/ja/gtd-5.html&gt;
WHERE { 

 :Tokyo meteo:forecast ?forecast .
 ?forecast meteo:predicted &quot;2013-01-08T00:00:00Z&quot;^^xsd:dateTime ;
           meteo:temperature ?temp .
 ?temp meteo:celsius ?tempC .
}
